Feature pbota 2
bogdibota/dashboard pull request #6
Opened 2019-03-20 15:37 UTC by paulbota

https://github.com/bogdibota/dashboard/issues/2

2019-03-20 15:37 UTC, paulbota commented
![command-status](https://user-images.githubusercontent.com/5650397/54697795-e1caeb00-4b36-11e9-9622-d60d59facf8c.gif)

2019-03-20 16:54 UTC, bogdibota commented
all the components under `components/*` are dumb components. please don't link them with redux

2019-03-20 16:57 UTC, bogdibota requested changes

2019-03-20 16:57 UTC, bogdibota commented on src/components/statusLight/StatusLight.css
> +div .container {
refactor this with `withStyles`
animation also works: see https://github.com/mui-org/material-ui/blob/353c0aedc50de8bb2c09626e520d7cc16ac461dc/packages/material-ui/src/ButtonBase/TouchRipple.js#L84

2019-03-20 16:57 UTC, bogdibota commented on src/components/statusLight/StatusLight.js
> +        {status ?
maybe a switch will look better here. should be easier to read

2019-03-20 16:57 UTC, bogdibota commented on src/components/command/tabs/StatusTab.js
> +export default connect(mapStateToProps)(StatusTab);
see comment on MR. this should be a dumb component

2019-03-20 16:57 UTC, bogdibota commented on src/components/commandTree/TreeItem.js
> +const TreeItemWithStyles = withStyles(styles)(connect(mapStateToProps)(TreeItem));
see comment on MR. this should be a dumb component

2019-03-21 08:17 UTC, bogdibota approved these changes

2019-03-21 08:17 UTC, merged